//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanEMIDetail
    {
        public int EMIID { get; set; }
        public Nullable<int> AccNum { get; set; }
        public Nullable<System.DateTime> EMIDate { get; set; }
        public Nullable<decimal> EMIAmount { get; set; }
        public string EMIStatus { get; set; }
        public Nullable<System.DateTime> EMIReminder { get; set; }
        public Nullable<decimal> RemainingBalance { get; set; }
    
        public virtual LoanAccountDetail LoanAccountDetail { get; set; }
    }
}
